### ISSUE TITLE
Data.Typeable.Internal is not available in GHC 8.2.1

### ISSUE THREAD

**Issue by peti** [hspec/hspec#323] opened 2017-07-02 08:04 UTC
Citing from https://nix-cache.s3.amazonaws.com/log/m7n5zn91k6fp0jvdxfcgdzmnpw5h3y1a-hspec-meta-2.3.2.drv:

~~~
hspec-core/src/Test/Hspec/Compat.hs:54:1: error:
    Could not find module ‘Data.Typeable.Internal’
    it is a hidden module in the package ‘base-4.10.0.0’
    Use -v to see a list of the files searched for.
   |
54 | import           Data.Typeable.Internal (tyConModule, tyConName)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[19 of 26] Compiling Test.Hspec.Timer ( hspec-core/src/Test/Hspec/Timer.hs, dist/build/Test/Hspec/Timer.o )
~~~~

**Comment by sol** [comment] 2017-07-02 23:43
@peti Hey, thanks a lot for taking the time to open this issue.  I don't know what changed here and I do not have access to GHC `8.2.1` right now. PRs are more than welcome.

**Comment by peti** [comment] 2017-07-04 13:08
Well, I could probably provide a PR. I cannot find the source code for `hspec-meta`, however. Where does that repository live?

**Comment by sol** [comment] 2017-07-05 23:26
It's in this repository on branch `hspec-meta`.

**Comment by sol** [comment] 2017-07-05 23:29
I can't reproduce this with `8.2.0.20170623` from https://launchpad.net/~hvr/+archive/ubuntu/ghc.

**Comment by peti** [comment] 2017-07-06 13:02
Well, I don't know anything about that compiler. I'm using `ghc-8.2.1-rc3`, which has a slightly different internal version number, `ghc-8.2.0.20170704` I think. Anyhow, I'll check whether I can fix the build and contribute a patch.

**Comment by peti** [comment] 2017-07-06 13:42
The current git HEAD at e6ac07bea20b23d556b7d77a7aada22acfbfdc15 compiles fine. Is that version going to show up on Hackage any time soon?

**Comment by sol** [comment] 2017-07-07 06:14
@peti The issue was that `hspec-meta` was too old.  Fixed on Hackage.

**Closed by sol** 2017-07-07 06:14 UTC
