### ISSUE TITLE
Print progress while a test suite is running

### ISSUE THREAD

**Issue by nikita-volkov** [hspec/hspec#231] opened 2015-04-28 15:34 UTC
I have a heavy test suite, which takes quite some time to run. I'd love to see it's progress instead of a blank screen while it runs. To see when the results of each completed test as soon as it's finished. 

Is that possible to do currently? If not, then I request that as a feature.

**Comment by sol** [comment] 2015-04-28 16:32
Yes, it's possible.  How exactly do you currently run your tests?

**Comment by sol** [comment] 2015-04-28 16:39
Does the following README provide a solution that works for you?

https://github.com/hspec/hspec-example/blob/master/README.md

Specifically, would

    $ cabal configure --enable-tests --disable-optimization && cabal build && ./dist/build/spec/spec

do what you want?

**Comment by nikita-volkov** [comment] 2015-04-28 18:55
Nope. Nothing of that helps. 

Can it have something to do with my setup?

```haskell

main =
  hspec $ do

    context "Retrieving detail pages URLs list" $ do

      result <- 
        runIO $
        fmap (fmap (fmap (\(_, _, _, x) -> x))) $
        Scraper.run $ Scraper.searchResults $ Left (Nothing, Nothing, Nothing)

      it "should not fail" $ do
        shouldSatisfy result (not . isLeft)

      forM_ result $ mapM_ $ \url -> do
        context ("URL " <> show url) $ do
          context "Scraping" $ do
            result <- runIO $ Scraper.run $ Scraper.scrape Parser.courseDetailsPage (convert url)
            it "should not fail" $ do
              shouldSatisfy result (not . isLeft)
```

**Comment by sol** [comment] 2015-04-28 20:56
I guess the problem is the usage of `runIO`.  The [documentation](http://hackage.haskell.org/package/hspec-2.1.7/docs/Test-Hspec.html#v:runIO) states:

> Run an `IO` action while constructing the spec tree.
> 
> `SpecM` is a monad to construct a spec tree, without executing any spec items. `runIO` allows you to run `IO` actions during this construction phase. The `IO` action is always run when the spec tree is constructed (e.g. even when `--dry-run` is specified). If you do not need the result of the `IO` action to construct the spec tree, `beforeAll` may be more suitable for your use case.

That means `runIO` is run during spec construction time.  It is meant to run lightweight initialization code (e.g. construction `MVar`s for some of Hspec's low-level primitives) that is fine to run even if we never plan to run the specs (e.g. on `--dry-run`).  It is _not_ meant for running code that has side effects or for your actual spec code;  that should be done within your individual spec items (the block after an `it`).

If you want, you can take a look at any of my GitHub projects for reference (none of them will use `runIO`), e.g. https://github.com/hspec/autospec.

**Comment by sol** [comment] 2015-04-28 21:19
For your given example, the following may work:
```haskell
main :: IO ()
main = hspec $ do
  context "Retrieving detail pages URLs list" $ do
    it "should not fail" $ do
      result <- fmap (fmap (fmap (\(_, _, _, x) -> x))) $ Scraper.run $ Scraper.searchResults $ Left (Nothing, Nothing, Nothing)
      result `shouldSatisfy` isRight
                           
    forM_ result $ mapM_ $ \url -> do
      context ("URL " <> show url) $ do
        context "Scraping" $ do
          it "should not fail" $ do
            result <- Scraper.run $ Scraper.scrape Parser.courseDetailsPage (convert url)
            result `shouldSatisfy` isRight
```

**Comment by nikita-volkov** [comment] 2015-04-29 04:59
Thank you! Your corrections to my code have fixed the original issue.

However, with these corrections now I can't run multiple tests against the data, which I receive using `runIO`. Consider the following snippet, where I add another test in my original code:

```haskell
          context "Scraping" $ do
            result <- runIO $ Scraper.run $ Scraper.retrying $ Scraper.scrape Parser.courseDetailsPage (convert url)
            it "should not fail" $ 
              shouldSatisfy result (not . isLeft)
            -- An extra test on the "result":
            it "produces a non-empty list" $ 
              shouldSatisfy result (either (const False) (not . null))
```

You can see, how it clearly follows the logic of a context and subject attribution. I.e., in the `context` block I do actually establish a context by receiving the context data, which I then go to run multiple tests against. The `it` cases become just that: simple and clear singular tests attributed with textual labels, which contain only the test code.

I love the clear semantics behind this approach. And I don't see any reasons why it should block the incremental output. So I guess I'm now requalifying this issue to a request for fixing that.

**Comment by sol** [comment] 2015-04-30 06:12
@nikita-volkov Sorry for the late reply!

The main focus of Hspec is provide a convenient and powerful mechanism for construct test-suites with a structure that is know statically (where the structure of the test suite does not depend on the result of IO actions).  So your use case may be somewhat out of scope for this project.

However, there are still things that you can try.  If the structure of your test suite depends on the result of an IO action, you have to use `runIO`.  In case where you merely want to access the result of an IO action in multiple `it` blocks you can `beforeAll`.  For your last example that would like so:

```haskell
  context "Scraping" $ do
    beforeAll (Scraper.run $ Scraper.retrying $ Scraper.scrape Parser.courseDetailsPage (convert url)) $ do
      it "should not fail" $ \result -> do
        shouldSatisfy result (not . isLeft)

      it "produces a non-empty list" $ \result -> do
        shouldSatisfy result (either (const False) (not . null))
```

Note that `runIO` is run when the spec tree is constructed.  In contrast `beforeAll` is only executed when the test suite is actually executed _and_ when the result is needed for the first time.  For that reason you will not get any progress reporting for `runIO`, but for `beforeAll` progress reporting works.

It may be possible to use a combination of `runIO` and `beforeAll` to get a better approximation of your desired behaviour.  That means use `beforeAll` instead of `runIO` when ever possible and only resort to `runIO` when the structure of your test suite depends on the result of that `IO` action.

Hope that helps.

**Comment by nikita-volkov** [comment] 2015-04-30 06:47
Thanks for your help!

**Comment by sol** [comment] 2015-05-05 16:22
Closing.

**Closed by sol** 2015-05-05 16:22 UTC
