### ISSUE TITLE
Documentation examples for QuickCheck don't work anymore

### ISSUE THREAD

**Issue by reygoch** [hspec/hspec#272] opened 2016-08-08 12:15 UTC
I'm getting a following error for examples on your [page](http://hspec.github.io/index.html) :

```
spec.hs:11:5: error:
    * Couldn't match type `Arg Property' with `()'
      Expected type: hspec-core-2.2.3:Test.Hspec.Core.Spec.Monad.SpecM
                       () ()
        Actual type: SpecWith (Arg Property)
    * In a stmt of a 'do' block:
        it "returns the first element of an *arbitrary* list"
        $ property $ \ x xs -> head (x : xs) == (x :: Int)
      In the second argument of `($)', namely
        `do { it "returns the first element of a list"
              $ do { head [23 .. ] `shouldBe` (23 :: Int) };
              it "returns the first element of an *arbitrary* list"
              $ property $ \ x xs -> head (x : xs) == (x :: Int);
              it "throws an exception if used with an empty list"
              $ do { evaluate (head []) `shouldThrow` anyException } }'
      In a stmt of a 'do' block:
        describe "Prelude.head"
        $ do { it "returns the first element of a list"
               $ do { head [23 .. ] `shouldBe` (23 :: Int) };
               it "returns the first element of an *arbitrary* list"
               $ property $ \ x xs -> head (x : xs) == (x :: Int);
               it "throws an exception if used with an empty list"
               $ do { evaluate (head []) `shouldThrow` anyException } }
```

This is example that produces that error message :

```
import Test.Hspec
import Test.QuickCheck
import Control.Exception (evaluate)

main :: IO ()
main = hspec $ do
  describe "Prelude.head" $ do
    it "returns the first element of a list" $ do
      head [23 ..] `shouldBe` (23 :: Int)

    it "returns the first element of an *arbitrary* list" $
      property $ \x xs -> head (x:xs) == (x :: Int)

    it "throws an exception if used with an empty list" $ do
      evaluate (head []) `shouldThrow` anyException
```

**Comment by sol** [comment] 2016-10-08 05:03
@reygoch I can't reproduce this. Can you try again? If it still fails, can you provide a git repository that illustrates the issue.

**Comment by sol** [comment] 2016-10-18 16:45
As I can not reproduce this, I am closing this. @reygoch please reopen with a fully self-contained example if the problem persists.

**Comment by fabianhjr** [comment] 2016-11-07 02:29
Hello, I just got this issue. Was able to reproduce on

```
> uname -mrs
Linux 4.8.6-1-ARCH x86_64
> ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
```

There has been some issues around the new major GHC release. Might be related? (Will try with ghc 7.x)

**Comment by sol** [comment] 2016-11-07 04:49
@fabianhjr can you give exact steps to reproduce this.

**Comment by fabianhjr** [comment] 2016-11-07 15:31
Ok, so tried it again with an empty project and it did work. ( https://github.com/fabianhjr/HaskellScaffold )

I am probably dumb and had an error somewhere in the spec. I am redoing the failing ones and it is working again. :|

(In an attempt to debug the error I pasted the examples as @reygoch might have been into something)

**Comment by sol** [comment] 2016-11-07 15:53
I kind of suspect that you had multiple versions of QuickCheck installed.

**Closed** 2016-11-08 02:41 UTC
