### ISSUE TITLE
Test suite fails on i686 (32-bit)

### ISSUE THREAD

**Issue by nh2** [hspec/hspec#431] opened 2020-03-28 02:38 UTC
https://nix-cache.s3.amazonaws.com/log/vhbn2z10qrl9by4z2rrjc9gj98ixkv93-hspec-core-2.7.1.drv (from [here](https://hydra.nixos.org/build/115533628)) shows failures that seem to happen only on 32-bit Linux.

Perhaps this is related to `Int` being used in the test itself, or `StdGen`?

Could the tests be written so that they pass on both 32- and 64-bit?

```
Failures:

  test/Test/Hspec/Core/QuickCheckUtilSpec.hs:96:9: 
  1) Test.Hspec.Core.QuickCheckUtil.parseQuickCheckResult, with NoExpectedFailure, includes verbose output
       expected: QuickCheckResult {quickCheckResultNumTests = 2, quickCheckResultInfo = "Passed:\n0\n\nPassed:\n28", quickCheckResultStatus = QuickCheckOtherFailure "Passed 2 tests (expected failure)."}
        but got: QuickCheckResult {quickCheckResultNumTests = 2, quickCheckResultInfo = "Passed:\n0\n\nPassed:\n-45", quickCheckResultStatus = QuickCheckOtherFailure "Passed 2 tests (expected failure)."}

  To rerun use: --match "/Test.Hspec.Core.QuickCheckUtil/parseQuickCheckResult/with NoExpectedFailure/includes verbose output/"

  test/Test/Hspec/Core/QuickCheckUtilSpec.hs:106:11: 
  2) Test.Hspec.Core.QuickCheckUtil.parseQuickCheckResult, with cover, without checkCoverage, parses result
       expected: QuickCheckResult {quickCheckResultNumTests = 100, quickCheckResultInfo = "+++ OK, passed 100 tests.\n\nOnly 0% is 23, but expected 10%", quickCheckResultStatus = QuickCheckSuccess}
        but got: QuickCheckResult {quickCheckResultNumTests = 100, quickCheckResultInfo = "+++ OK, passed 100 tests (1% is 23).\n\nOnly 1% is 23, but expected 10%", quickCheckResultStatus = QuickCheckSuccess}

  To rerun use: --match "/Test.Hspec.Core.QuickCheckUtil/parseQuickCheckResult/with cover/without checkCoverage/parses result/"

  test/Test/Hspec/Core/QuickCheckUtilSpec.hs:122:11: 
  3) Test.Hspec.Core.QuickCheckUtil.parseQuickCheckResult, with cover, without checkCoverage, includes verbose output
       expected: QuickCheckResult {quickCheckResultNumTests = 2, quickCheckResultInfo = "Passed:\n0\n\nPassed:\n28\n\n+++ OK, passed 2 tests.\n\nOnly 0% is 23, but expected 10%", quickCheckResultStatus = QuickCheckSuccess}
        but got: QuickCheckResult {quickCheckResultNumTests = 2, quickCheckResultInfo = "Passed:\n0\n\nPassed:\n-45\n\n+++ OK, passed 2 tests.\n\nOnly 0% is 23, but expected 10%", quickCheckResultStatus = QuickCheckSuccess}

  To rerun use: --match "/Test.Hspec.Core.QuickCheckUtil/parseQuickCheckResult/with cover/without checkCoverage/includes verbose output/"

  test/Test/Hspec/Core/QuickCheckUtilSpec.hs:143:11: 
  4) Test.Hspec.Core.QuickCheckUtil.parseQuickCheckResult, with cover, with checkCoverage, parses result
       expected: QuickCheckResult {quickCheckResultNumTests = 400, quickCheckResultInfo = "", quickCheckResultStatus = QuickCheckFailure (QCFailure {quickCheckFailureNumShrinks = 0, quickCheckFailureException = Nothing, quickCheckFailureReason = "Insufficient coverage", quickCheckFailureCounterexample = [" 0.8% is 23","","Only 0.8% is 23, but expected 10.0%"]})}
        but got: QuickCheckResult {quickCheckResultNumTests = 400, quickCheckResultInfo = "", quickCheckResultStatus = QuickCheckFailure (QCFailure {quickCheckFailureNumShrinks = 0, quickCheckFailureException = Nothing, quickCheckFailureReason = "Insufficient coverage", quickCheckFailureCounterexample = [" 0.3% is 23","","Only 0.3% is 23, but expected 10.0%"]})}

  To rerun use: --match "/Test.Hspec.Core.QuickCheckUtil/parseQuickCheckResult/with cover/with checkCoverage/parses result/"

  test/Test/Hspec/Core/QuickCheckUtilSpec.hs:148:11: 
  5) Test.Hspec.Core.QuickCheckUtil.parseQuickCheckResult, with cover, with checkCoverage, includes verbose output
       expected: QuickCheckResult {quickCheckResultNumTests = 400, quickCheckResultInfo = "Passed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:", quickCheckResultStatus = QuickCheckFailure (QCFailure {quickCheckFailureNumShrinks = 0, quickCheckFailureException = Nothing, quickCheckFailureReason = "Insufficient coverage", quickCheckFailureCounterexample = [" 0.8% is 23","","Only 0.8% is 23, but expected 10.0%"]})}
        but got: QuickCheckResult {quickCheckResultNumTests = 400, quickCheckResultInfo = "Passed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:\n\nPassed:", quickCheckResultStatus = QuickCheckFailure (QCFailure {quickCheckFailureNumShrinks = 0, quickCheckFailureException = Nothing, quickCheckFailureReason = "Insufficient coverage", quickCheckFailureCounterexample = [" 0.3% is 23","","Only 0.3% is 23, but expected 10.0%"]})}

  To rerun use: --match "/Test.Hspec.Core.QuickCheckUtil/parseQuickCheckResult/with cover/with checkCoverage/includes verbose output/"

  test/Test/Hspec/Core/QuickCheckUtilSpec.hs:161:11: 
  6) Test.Hspec.Core.QuickCheckUtil.parseQuickCheckResult, with Failure, with single-line failure reason, parses result
       expected: QuickCheckResult {quickCheckResultNumTests = 3, quickCheckResultInfo = "", quickCheckResultStatus = QuickCheckFailure (QCFailure {quickCheckFailureNumShrinks = 1, quickCheckFailureException = Nothing, quickCheckFailureReason = "Falsified", quickCheckFailureCounterexample = ["1"]})}
        but got: QuickCheckResult {quickCheckResultNumTests = 3, quickCheckResultInfo = "", quickCheckResultStatus = QuickCheckFailure (QCFailure {quickCheckFailureNumShrinks = 0, quickCheckFailureException = Nothing, quickCheckFailureReason = "Falsified", quickCheckFailureCounterexample = ["1"]})}

  To rerun use: --match "/Test.Hspec.Core.QuickCheckUtil/parseQuickCheckResult/with Failure/with single-line failure reason/parses result/"

  test/Test/Hspec/Core/QuickCheckUtilSpec.hs:184:11: 
  7) Test.Hspec.Core.QuickCheckUtil.parseQuickCheckResult, with Failure, with single-line failure reason, includes verbose output
       expected: QuickCheckResult {quickCheckResultNumTests = 3, quickCheckResultInfo = "Passed:\n0\n\nPassed:\n-1\n\nFailed:\n2\n\nPassed:\n0\n\nFailed:\n1\n\nPassed:\n0", quickCheckResultStatus = QuickCheckFailure (QCFailure {quickCheckFailureNumShrinks = 1, quickCheckFailureException = Nothing, quickCheckFailureReason = "Falsified", quickCheckFailureCounterexample = ["1"]})}
        but got: QuickCheckResult {quickCheckResultNumTests = 3, quickCheckResultInfo = "Passed:\n0\n\nPassed:\n-1\n\nFailed:\n1\n\nPassed:\n0", quickCheckResultStatus = QuickCheckFailure (QCFailure {quickCheckFailureNumShrinks = 0, quickCheckFailureException = Nothing, quickCheckFailureReason = "Falsified", quickCheckFailureCounterexample = ["1"]})}

  To rerun use: --match "/Test.Hspec.Core.QuickCheckUtil/parseQuickCheckResult/with Failure/with single-line failure reason/includes verbose output/"

  test/Test/Hspec/Core/QuickCheckUtilSpec.hs:195:11: 
  8) Test.Hspec.Core.QuickCheckUtil.parseQuickCheckResult, with Failure, with multi-line failure reason, parses result
       expected: QuickCheckResult {quickCheckResultNumTests = 3, quickCheckResultInfo = "", quickCheckResultStatus = QuickCheckFailure (QCFailure {quickCheckFailureNumShrinks = 0, quickCheckFailureException = Nothing, quickCheckFailureReason = "foo\nbar", quickCheckFailureCounterexample = ["2"]})}
        but got: QuickCheckResult {quickCheckResultNumTests = 6, quickCheckResultInfo = "", quickCheckResultStatus = QuickCheckFailure (QCFailure {quickCheckFailureNumShrinks = 0, quickCheckFailureException = Nothing, quickCheckFailureReason = "foo\nbar", quickCheckFailureCounterexample = ["2"]})}

  To rerun use: --match "/Test.Hspec.Core.QuickCheckUtil/parseQuickCheckResult/with Failure/with multi-line failure reason/parses result/"

  test/Test/Hspec/Core/QuickCheckUtilSpec.hs:214:11: 
  9) Test.Hspec.Core.QuickCheckUtil.parseQuickCheckResult, with Failure, with multi-line failure reason, includes verbose output
       expected: QuickCheckResult {quickCheckResultNumTests = 3, quickCheckResultInfo = "Passed:\n0\n\nPassed:\n-1\n\nFailed:\n2\n\nPassed:\n0\n\nPassed:\n1", quickCheckResultStatus = QuickCheckFailure (QCFailure {quickCheckFailureNumShrinks = 0, quickCheckFailureException = Nothing, quickCheckFailureReason = "foo\nbar", quickCheckFailureCounterexample = ["2"]})}
        but got: QuickCheckResult {quickCheckResultNumTests = 6, quickCheckResultInfo = "Passed:\n0\n\nPassed:\n-1\n\nPassed:\n1\n\nPassed:\n-2\n\nPassed:\n-4\n\nFailed:\n2\n\nPassed:\n0\n\nPassed:\n1", quickCheckResultStatus = QuickCheckFailure (QCFailure {quickCheckFailureNumShrinks = 0, quickCheckFailureException = Nothing, quickCheckFailureReason = "foo\nbar", quickCheckFailureCounterexample = ["2"]})}

  To rerun use: --match "/Test.Hspec.Core.QuickCheckUtil/parseQuickCheckResult/with Failure/with multi-line failure reason/includes verbose output/"

Randomized with seed 1842633505
```

**Comment by sol** [comment] 2020-04-01 16:32
@nh2 if rewriting the tests by e.g. using `Int64` (or `Integer`) solves the issue, then I'm more than happy to accept a patch.

**Comment by sol** [comment] 2021-04-15 20:24
Can't reproduce on a Vagrant box with `ubuntu/xenial32`.

I'm going to close this, but still happy to accept any patches.

**Closed by sol** 2021-04-15 20:24 UTC
