### ISSUE TITLE
Error with dependency in old version of hspec

### ISSUE THREAD

**Issue by NorfairKing** [hspec/hspec#382] opened 2018-09-30 19:32 UTC
As discussed:

```
Warning: Inferring license from file LICENSE failed!

Warning: Inferring license from file LICENSE failed!

Warning: /home/syd/smos/.stack-work/downloaded/rJrN5jiAxn7A/hspec.cabal was generated with a newer version of hpack,
         please upgrade and try again.
/home/syd/smos/.stack-work/downloaded/rJrN5jiAxn7A/hspec-core/package.yaml: Error while parsing $.tests.spec.build-tools - invalid dependency "hspec-meta:hspec-meta-discover"```

**Comment by sol** [comment] 2018-11-03 20:37
@NorfairKing thanks for bringing this up.  It's useful for me to be aware of this kind of things! So that helps a lot!

I think the issue here is that `stack` ships an outdated version of `hpack`.  So this is not really related to `hspec` itself.  I've been lobbying in the past to somehow ensure that `stack` ships recent versions of `hpack`.  While I understand that being conservative about upgrading dependencies is important to ensure reproducibility, many of the pain points with `hpack` and `stack` are caused by `hpack` being outdated.  I'm not sure what the right solution is here and I understand that I see this mainly from the perspective of the maintainer of `hpack`.  At least historically, I also haven't been a heavy stack user (even though that changed recently, due to client requirements). It may make sense to bring this up as a `stack` issue.

Closing.

**Closed by sol** 2018-11-03 20:37 UTC
